colorScheme = "beige"
defaultAppearance = "light"
autoSwitchAppearance = false

defaultThemeColor = "#faf4e8"

enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true
enableImageWebp = true

fingerprintAlgorithm = "sha256"

[header]
  layout = "hybrid"
  showTitle = true

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "profile"
  homepageImage = ""
  showRecent = true
  showRecentItems = 3
  recentLimit = 3
  cardView = true

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = false
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showComments = false
  sharingLinks = ["linkedin", "x-twitter", "email"]

[list]
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = false
  showTaxonomies = true
  groupByYear = true
  paginationWidth = 1
  cardView = true
  cardViewScreenWidth = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[verification]
